debug:
  update_interval: 5s

logger:
  level: VERY_VERBOSE
  logs: 
    mdns: WARN
    scd4x: WARN
    sgp4x: WARN
    scheduler: WARN 
    api.service: WARN
    api.connection: WARN
    json: WARN
    ld2410: WARN
    ledc.output: WARN
    esp32_ble_tracker: WARN
    esp32_ble: WARN
    bluetooth_proxy.connection: WARN
    bluetooth_proxy: WARN
    adc: WARN
    
    i2c: WARN
    mpm10: WARN
    wifi_info: WARN
    wifi_signal: WARN
    sensor: WARN
    resistance: WARN
    binary_sensor: WARN

psram:
  mode: octal
  speed: 80MHz

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"